/**
 * Scaffold helper — creates a new extension/module/trigger project structure on disk.
 *
 * Shared between:
 *   - `fmx init` (packages/cli/src/commands/init.ts) — CLI command
 *   - MCP scaffold-adapter (src/engine/codeEngine/mcp/scaffold-adapter.ts) — MCP tool
 *     `codeengine_scaffold` invoked locally by AI clients.
 *
 * Pure filesystem operation — no HTTP, no token required. Idempotency guarded by
 * `existsSync(targetDir)` unless `force: true`.
 *
 * @package @fluxomind/cli (local helper)
 */

import { mkdirSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';

export type TemplateKind = 'extension' | 'trigger' | 'module';

export interface CreateProjectInput {
  /** Project name — must be kebab-case [a-z][a-z0-9]*(-[a-z0-9]+)* */
  name: string;
  /** Project template kind */
  type: TemplateKind;
  /** Parent directory where `<name>/` will be created (default: process.cwd()) */
  targetDir?: string;
  /** If true, skip existsSync check (overwrites). Default false. */
  force?: boolean;
}

export interface CreateProjectResult {
  path: string;
  files: string[];
}

export class ScaffoldError extends Error {
  readonly code: 'INVALID_NAME' | 'INVALID_TYPE' | 'DIR_EXISTS' | 'WRITE_FAILED';

  constructor(code: 'INVALID_NAME' | 'INVALID_TYPE' | 'DIR_EXISTS' | 'WRITE_FAILED', message: string) {
    super(message);
    this.name = 'ScaffoldError';
    this.code = code;
  }
}

export const README_PLACEHOLDER = '{EXTENSION_NAME}';

export const GITIGNORE_TEMPLATE = `# Dependencies
node_modules/
dist/
build/

# Environment & secrets
.env
.env.*
!.env.example

# Fluxomind CLI local state
.fmx/

# Credentials
*.pem
*.key
*.crt
*.p12
*.pfx

# AI clients local cache (local-only)
.continue/.cache/
.claude/.cache/

# OS
.DS_Store
Thumbs.db

# Editor
.vscode/*.log
.idea/
*.swp

# Logs
*.log
npm-debug.log*
yarn-debug.log*
pnpm-debug.log*

# Coverage
coverage/
.nyc_output/
`;

export const README_TEMPLATE = `# {EXTENSION_NAME}

A Fluxomind extension — generated by \`fmx init\`.

## Getting started

\`\`\`bash
fmx dev        # watch mode
fmx deploy     # deploy to sandbox
fmx logs --tail
\`\`\`

## Security Recommendations

This repository was created with \`visibility: private\` by default. For production workflows, we recommend enabling the following GitHub native features via Settings:

- **[Branch protection rules](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches)** — require PR + review + status checks, disallow force-push on \`main\`
- **[Dependabot alerts](https://docs.github.com/en/code-security/dependabot/dependabot-alerts/about-dependabot-alerts)** — weekly scan for vulnerable dependencies
- **[Secret Scanning](https://docs.github.com/en/code-security/secret-scanning/about-secret-scanning)** — auto-detect committed secrets (free for private repos since 2023)
- **[Tag protection rules](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-tag-protection-rules)** — restrict who can push \`v*\` tags (controls production deploys)

Fluxomind does not enforce these — they are governance decisions of your team via GitHub Settings.

## Links

- [Fluxomind Developer Guide](https://docs.fluxomind.dev/fmcode)
- [profile-dev playbook](https://github.com/fluxomind/platform/blob/main/fmd-docs/_playbook/fmcode/profile-dev.md)
`;

export function renderReadme(name: string): string {
  return README_TEMPLATE.split(README_PLACEHOLDER).join(name);
}

export function isKebabCase(name: string): boolean {
  return /^[a-z][a-z0-9]*(-[a-z0-9]+)*$/.test(name);
}

export function isValidTemplateKind(value: string): value is TemplateKind {
  return value === 'extension' || value === 'trigger' || value === 'module';
}

function entryPoint(kind: TemplateKind): string {
  if (kind === 'module') {
    return `// Module entry point\nexport const version = '0.1.0';\n`;
  }
  const signature =
    kind === 'trigger'
      ? 'const { operation, record, oldRecord } = ctx;\n  fm.utils.log(`Trigger: ${operation} on ${ctx.objectApiName}`);'
      : 'fm.utils.log(`Trigger: ${ctx.operation}`);';
  return `export default async function handler(ctx: fm.TriggerContext) {\n  ${signature}\n  return { success: true };\n}\n`;
}

function testFile(kind: TemplateKind): string {
  return `describe('${kind}', () => {\n  it('should pass', () => {\n    expect(true).toBe(true);\n  });\n});\n`;
}

function tsConfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module: 'ESNext',
        moduleResolution: 'bundler',
        strict: true,
        outDir: './dist',
        rootDir: './src',
      },
      include: ['src/**/*.ts', 'types/fm.d.ts'],
    },
    null,
    2,
  );
}

function generateManifest(name: string, kind: TemplateKind): string {
  return `[extension]\nname = "${name}"\nversion = "0.1.0"\ndescription = "A Fluxomind ${kind}"\nauthor = "unknown"\nengine_version = "0.1.0"\n\n[permissions]\ndata = ["read"]\n`;
}

interface TemplateFile {
  path: string;
  content: string;
}

export function buildTemplateFiles(name: string, kind: TemplateKind): TemplateFile[] {
  const files: TemplateFile[] = [
    { path: 'manifest.toml', content: generateManifest(name, kind) },
    { path: 'src/index.ts', content: entryPoint(kind) },
    { path: 'tests/index.test.ts', content: testFile(kind) },
    { path: 'tsconfig.json', content: tsConfig() },
    { path: 'types/fm.d.ts', content: '/// <reference types="@fluxomind/sdk" />\n' },
    { path: '.gitignore', content: GITIGNORE_TEMPLATE },
    { path: 'README.md', content: renderReadme(name) },
  ];
  if (kind === 'module') {
    files.splice(2, 0, { path: 'src/objects.toml', content: '# Define custom objects for this module\n' });
  }
  return files;
}

/**
 * Create a new project on disk. Idempotent: fails if targetDir/name exists unless `force: true`.
 */
export function createProject(input: CreateProjectInput): CreateProjectResult {
  if (!isKebabCase(input.name)) {
    throw new ScaffoldError(
      'INVALID_NAME',
      `Invalid project name "${input.name}". Use kebab-case (e.g., my-extension).`,
    );
  }

  if (!isValidTemplateKind(input.type)) {
    throw new ScaffoldError(
      'INVALID_TYPE',
      `Invalid template type "${input.type}". Use: extension, trigger, module.`,
    );
  }

  const parentDir = input.targetDir ?? process.cwd();
  const projectDir = join(parentDir, input.name);

  if (existsSync(projectDir) && !input.force) {
    throw new ScaffoldError('DIR_EXISTS', `Directory "${input.name}" already exists.`);
  }

  try {
    mkdirSync(projectDir, { recursive: true });

    const templateFiles = buildTemplateFiles(input.name, input.type);
    const writtenPaths: string[] = [];

    for (const file of templateFiles) {
      const filePath = join(projectDir, file.path);
      mkdirSync(join(filePath, '..'), { recursive: true });
      writeFileSync(filePath, file.content, 'utf-8');
      writtenPaths.push(file.path);
    }

    return { path: projectDir, files: writtenPaths };
  } catch (err) {
    if (err instanceof ScaffoldError) throw err;
    throw new ScaffoldError(
      'WRITE_FAILED',
      `Failed to scaffold project: ${err instanceof Error ? err.message : String(err)}`,
    );
  }
}
